# Example power capping configuration
# strategy can be CONTINOUS_EQUAL, BINARY_GREEDY or EDP_GRADIENT_OPT
strategy=CONTINOUS_EQUAL
# cpu_min_powercap and gpu_min_powercap are used for CONTINOUS_EQUAL strategy
cpu_min_powercap=0.1
gpu_min_powercap=0.1
# start_powercap is used for EDP_GRADIENT_OPT strategy
start_powercap=1.0
